---
apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: silly-demo
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  immediateDeploy: true
  connection:
    postgres:
      host:
        valueFrom:
          secretKeyRef:
            name: silly-demo
            key: endpoint
      user:
        valueFrom:
          secretKeyRef:
            name: silly-demo
            key: username
      password:
        valueFrom:
          secretKeyRef:
            name: silly-demo
            key: password
      port:
        value: "5432"
      dbname:
        value: silly-demo
---
apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: other-videos
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  database: silly-demo
  name: other-videos
  schema:
    postgres:
      primaryKey:
        - id
      columns:
        - name: id
          type: text
          constraints:
            notNull: true
        - name: title
          type: text
          constraints:
            notNull: true
