---

apiVersion: v1
kind: Secret
metadata:
  name: silly-demo-db-password
data:
  password: cG9zdGdyZXM=

---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: silly-demo-db
spec:
  id: silly-demo-db
  compositionSelector:
    matchLabels:
      provider: google-official
      db: postgresql
  parameters:
    version: "13"
    size: small
