configs:
  secret:
    argocdServerAdminPassword: "$2a$10$m3eTlEdRen0nS86c5Zph5u/bDFQMcWZYdG3NVdiyaACCqoxLJaz16"
    argocdServerAdminPasswordMtime: "2021-11-08T15:04:05Z"
  cm:
    application.resourceTrackingMethod: annotation
    timeout.reconciliation: 30s
    resource.customizations.health.devopstoolkitseries.com_SQLClaim: |
      hs = {}
      hs.status = "Healthy"
      synced = true
      for i, condition in ipairs(obj.status.conditions) do
        if condition.type == "Synced" and condition.status ~= "True"
          hs.status = "Degraded"
          synced_message = condition.reason
          if condition.message then
            synced_message = synced_message .. ": " ..condition.message
          end
        end
      end
      return hs
server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - argocd.127.0.0.1.nip.io
